api_platform:
  title: 'Suivi des apprenants ODC'
  description: "C'est une api de l'application de gestion des apprenants de la sonatel academy pour mieux suivre la progression des apprenants."
  version: '1.0.0'
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  #formats:
  #json: ['application/json']

  patch_formats:
    json: ['application/merge-patch+json']
    multipart: ['multipart/form-data']
  swagger:
    versions: [3]
  collection:
    pagination:
      enabled: true
      client_items_per_page: true
      items_per_page: 10
